packageExtensions:
  babel-loader@*:
    dependencies:
      '@babel/core': '*'
  puppeteer-extra@*:
    dependencies:
      puppeteer-extra-plugin-user-preferences: '*'
      puppeteer-extra-plugin-user-data-dir: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.3.0.cjs
